### PR TITLE
4 trying to run in portainer on rpi 4 and getting an error

### LINKED ISSUE #4: Trying to run in Portainer on RPi 4 and getting an error
Was wondering if you have any insights, the error I'm getting is: exec ./fr24feed: exec format error

Portainer Stack is: 
version: '2'
services:
  flightradar_feeder:
    network_mode: host
    image: marcelmaatkamp/flightradar24-feeder
    command: marcelmaatkamp/flightradar24-feeder --fr24key=**************
    restart: always
    privileged: true
    ports:
      - 8080:8080
      - 8754:8754
      - 30001:30001
      - 30002:30002
      - 30003:30003
      - 30334:30334      
I know you created the docker image and not a Portainer one but I'm not sure what's going on and would love any help if you have insights here.

### PR DESCRIPTION
**Pull request by marcelmaatkamp**

### CODE REVIEW

**Comment by marcelmaatkamp** [comment]
I've tested the new version and it succesfulky connected to my dongle and FL24.

**Comment by trippme** [comment]
I'm still getting this error: exec ./fr24feed: exec format error

Are there any obvious debugging steps I can do to help diagnose the problem?

**Comment by marcelmaatkamp** [comment]
Oh now I see, you're trying to run it on a rpi4 which is and is currently not a build-target for this container. I'll try to take a look to see if I can easily add that as a target.

**Comment by trippme** [comment]
That would be awesome.  I've never dockerized something so I'm not sure how
to do it.

**Pull request merged**
